# .sops.yaml - SOPS configuration for age encryption
keys:
  - &admin_h4wkeye age1dr7wep27gem82xw0rehwefrw4ksmjnacaktkwd89ly0tff5d0pgqke6m8r
  - &server_baxter age18xkegpxrpvdjm7qss0sxfy05sx56qq3drgf4e08dawq0jky37p5q44gkus

creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
    - age:
      - *admin_h4wkeye
      - *server_baxter
