# This file is auto-generated by nixos-generate-config
# It should be imported by configuration.nix

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  # This will be populated by nixos-generate-config during installation
  # For now, we provide minimal boot configuration that works with disko
  boot.initrd.availableKernelModules = [ "virtio_pci" "virtio_scsi" "ahci" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # Enable LVM and LUKS support
  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-partlabel/CRYPTROOT";

  # Filesystems will be configured by disko
  fileSystems."/" = lib.mkDefault { };
  fileSystems."/boot" = lib.mkDefault { };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}